// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type BlogPost struct {
	ID             string     `json:"id"`
	Title          string     `json:"title"`
	Slug           string     `json:"slug"`
	Excerpt        *string    `json:"excerpt,omitempty"`
	Content        string     `json:"content"`
	CoverImageURL  *string    `json:"coverImageUrl,omitempty"`
	Tags           []string   `json:"tags"`
	Status         BlogStatus `json:"status"`
	SeoTitle       *string    `json:"seoTitle,omitempty"`
	SeoDescription *string    `json:"seoDescription,omitempty"`
	PublishedAt    *string    `json:"publishedAt,omitempty"`
	CreatedAt      string     `json:"createdAt"`
	UpdatedAt      string     `json:"updatedAt"`
}

type CodeCategory struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Slug        string          `json:"slug"`
	Description *string         `json:"description,omitempty"`
	ParentID    *string         `json:"parentId,omitempty"`
	Color       *string         `json:"color,omitempty"`
	Icon        *string         `json:"icon,omitempty"`
	Children    []*CodeCategory `json:"children,omitempty"`
}

type CreateCodeCategoryInput struct {
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description,omitempty"`
	ParentID    *string `json:"parentId,omitempty"`
	Color       *string `json:"color,omitempty"`
	Icon        *string `json:"icon,omitempty"`
}

type CreateMonologueInput struct {
	Content        string      `json:"content"`
	ContentType    ContentType `json:"contentType"`
	CodeLanguage   *string     `json:"codeLanguage,omitempty"`
	CodeSnippet    *string     `json:"codeSnippet,omitempty"`
	Tags           []string    `json:"tags"`
	IsPublished    *bool       `json:"isPublished,omitempty"`
	URL            *string     `json:"url,omitempty"`
	Series         *string     `json:"series,omitempty"`
	Category       *string     `json:"category,omitempty"`
	CodeCategoryID *string     `json:"codeCategoryId,omitempty"`
	Difficulty     *Difficulty `json:"difficulty,omitempty"`
}

type Experience struct {
	ID           string   `json:"id"`
	Company      string   `json:"company"`
	Position     string   `json:"position"`
	Description  *string  `json:"description,omitempty"`
	StartDate    string   `json:"startDate"`
	EndDate      *string  `json:"endDate,omitempty"`
	IsCurrent    bool     `json:"isCurrent"`
	Technologies []string `json:"technologies"`
}

type LikeResponse struct {
	ID        string `json:"id"`
	LikeCount int    `json:"likeCount"`
	IsLiked   bool   `json:"isLiked"`
}

type MonologuesResponse struct {
	Nodes       []*Monologue `json:"nodes"`
	TotalCount  int          `json:"totalCount"`
	HasNextPage bool         `json:"hasNextPage"`
}

type Mutation struct {
}

type Profile struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Title       *string       `json:"title,omitempty"`
	Bio         *string       `json:"bio,omitempty"`
	AvatarURL   *string       `json:"avatarUrl,omitempty"`
	SocialLinks []*SocialLink `json:"socialLinks"`
}

type Query struct {
}

type RelatedContent struct {
	ID          string      `json:"id"`
	Title       string      `json:"title"`
	Type        ContentType `json:"type"`
	Excerpt     *string     `json:"excerpt,omitempty"`
	Tags        []string    `json:"tags"`
	PublishedAt string      `json:"publishedAt"`
	ReadTime    *int        `json:"readTime,omitempty"`
}

type SkillCategory struct {
	Category string   `json:"category"`
	Skills   []*Skill `json:"skills"`
}

type SocialLink struct {
	Platform string  `json:"platform"`
	URL      string  `json:"url"`
	Icon     *string `json:"icon,omitempty"`
}

type UpdateCodeCategoryInput struct {
	Name        *string `json:"name,omitempty"`
	Slug        *string `json:"slug,omitempty"`
	Description *string `json:"description,omitempty"`
	ParentID    *string `json:"parentId,omitempty"`
	Color       *string `json:"color,omitempty"`
	Icon        *string `json:"icon,omitempty"`
}

type UpdateMonologueInput struct {
	Content        *string      `json:"content,omitempty"`
	ContentType    *ContentType `json:"contentType,omitempty"`
	CodeLanguage   *string      `json:"codeLanguage,omitempty"`
	CodeSnippet    *string      `json:"codeSnippet,omitempty"`
	Tags           []string     `json:"tags,omitempty"`
	IsPublished    *bool        `json:"isPublished,omitempty"`
	URL            *string      `json:"url,omitempty"`
	Series         *string      `json:"series,omitempty"`
	Category       *string      `json:"category,omitempty"`
	CodeCategoryID *string      `json:"codeCategoryId,omitempty"`
	Difficulty     *Difficulty  `json:"difficulty,omitempty"`
}

type URLPreview struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	ImageURL    *string `json:"imageUrl,omitempty"`
	SiteName    *string `json:"siteName,omitempty"`
	URL         string  `json:"url"`
	Favicon     *string `json:"favicon,omitempty"`
	CreatedAt   string  `json:"createdAt"`
}

type BlogStatus string

const (
	BlogStatusDraft     BlogStatus = "DRAFT"
	BlogStatusPublished BlogStatus = "PUBLISHED"
	BlogStatusArchived  BlogStatus = "ARCHIVED"
)

var AllBlogStatus = []BlogStatus{
	BlogStatusDraft,
	BlogStatusPublished,
	BlogStatusArchived,
}

func (e BlogStatus) IsValid() bool {
	switch e {
	case BlogStatusDraft, BlogStatusPublished, BlogStatusArchived:
		return true
	}
	return false
}

func (e BlogStatus) String() string {
	return string(e)
}

func (e *BlogStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BlogStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BlogStatus", str)
	}
	return nil
}

func (e BlogStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BlogStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BlogStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ContentType string

const (
	ContentTypeText       ContentType = "TEXT"
	ContentTypeCode       ContentType = "CODE"
	ContentTypeImage      ContentType = "IMAGE"
	ContentTypeURLPreview ContentType = "URL_PREVIEW"
)

var AllContentType = []ContentType{
	ContentTypeText,
	ContentTypeCode,
	ContentTypeImage,
	ContentTypeURLPreview,
}

func (e ContentType) IsValid() bool {
	switch e {
	case ContentTypeText, ContentTypeCode, ContentTypeImage, ContentTypeURLPreview:
		return true
	}
	return false
}

func (e ContentType) String() string {
	return string(e)
}

func (e *ContentType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ContentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ContentType", str)
	}
	return nil
}

func (e ContentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ContentType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ContentType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Difficulty string

const (
	DifficultyBeginner     Difficulty = "BEGINNER"
	DifficultyIntermediate Difficulty = "INTERMEDIATE"
	DifficultyAdvanced     Difficulty = "ADVANCED"
)

var AllDifficulty = []Difficulty{
	DifficultyBeginner,
	DifficultyIntermediate,
	DifficultyAdvanced,
}

func (e Difficulty) IsValid() bool {
	switch e {
	case DifficultyBeginner, DifficultyIntermediate, DifficultyAdvanced:
		return true
	}
	return false
}

func (e Difficulty) String() string {
	return string(e)
}

func (e *Difficulty) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Difficulty(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Difficulty", str)
	}
	return nil
}

func (e Difficulty) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Difficulty) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Difficulty) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
